#!/bin/bash
#docker pull dockerskr/go113 -q
docker run --rm \
    -e GO111MODULE="on" \
    -e GOOS=darwin \
    -e GOARCH=amd64 \
    -e GOPROXY="https://goproxy.cn,http://go.xesv5.com/proxy,direct" \
    -e GOPRIVATE="*.100tal.com" \
    -e GONOPROXY="*.100tal.com" \
    -e GONOSUMDB="*.100tal.com" \
    -e GONOSUMDB="*.100tal.com" \
    -v "$GOPATH":/go \
    -v "$HOME"/.ssh:/root/.ssh \
    -v "$HOME"/.gitconfig:/root/.gitconfig \
    -v "$PWD":/usr/src/myapp \
    -w /usr/src/myapp \
    dockerskr/go113 go $@

